# Exercise 9: Tax Planning


Extend the existing inventory DataFrame by adding new columns that calculate the store's net income under different proposed sales tax rates.

1. Calculate the current net income for each product.
2. Create new columns representing net income after:
   - 15% tax
   - 20% tax
   - 25% tax
3. Compare the totals under each tax scenario to understand the financial impact.

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame([{'product_id':23, 'name':'computer', 'wholesale_price': 500,
        'retail_price':1000, 'sales':100},
        {'product_id':96, 'name':'Python Workout', 'wholesale_price': 35,
        'retail_price':75, 'sales':1000},
        {'product_id':97, 'name':'Pandas Workout', 'wholesale_price': 35,
        'retail_price':75, 'sales':500},
        {'product_id':15, 'name':'banana', 'wholesale_price': 0.5,
        'retail_price':1, 'sales':200},
        {'product_id':87, 'name':'sandwich', 'wholesale_price': 3,
        'retail_price':5, 'sales':300},
        ])

In [3]:
# Calculate current net income for each product
df['net_income'] = (df['retail_price'] - df['wholesale_price']) * df['sales']

In [4]:
df['after_15'] = df['net_income'] * 0.85
df['after_20'] = df['net_income'] * 0.80
df['after_25'] = df['net_income'] * 0.75

In [5]:
df

,product_id,name,wholesale_price,retail_price,sales,net_income,after_15,after_20,after_25
0,23,computer,500.0,1000,100,50000.0,42500.0,40000.0,37500.0
1,96,Python Workout,35.0,75,1000,40000.0,34000.0,32000.0,30000.0
2,97,Pandas Workout,35.0,75,500,20000.0,17000.0,16000.0,15000.0
3,15,banana,0.5,1,200,100.0,85.0,80.0,75.0
4,87,sandwich,3.0,5,300,600.0,510.0,480.0,450.0

In [9]:
print(f'Net income: {df['net_income'].sum()}')
print(f'Net income (after 15% tax): {df['after_15'].sum()}')
print(f'Net income (after 20% tax): {df['after_20'].sum()}')
print(f'Net income (after 25% tax): {df['after_25'].sum()}')

Net income: 226702
Net income (after 15% tax): 192696.69999999995
Net income (after 20% tax): 181361.6
Net income (after 25% tax): 170026.5

In [6]:
df.loc[[1,2], 'name']

1    Python Workout
2    Pandas Workout
Name: name, dtype: str

In [10]:
df.loc[[1,2], ['name','retail_price', 'sales']]

             name  retail_price  sales
1  Python Workout            75   1000
2  Pandas Workout            75    500

In [11]:
df.loc[df['sales'] >= 500]

,product_id,name,wholesale_price,retail_price,sales,net_income,after_15,after_20,after_25
1,96,Python Workout,35.0,75,1000,40000.0,34000.0,32000.0,30000.0
2,97,Pandas Workout,35.0,75,500,20000.0,17000.0,16000.0,15000.0