# Chapter 02 Data Frames — Exercise 09

Add sales tax of 15%, 20% and 25%

## Exercise

Add your summary of the task and any dataset notes here.

In [1]:
import pandas as pd
import numpy as np

## Solution

In [2]:
# method 1
df = pd.DataFrame([
    {'product_id': 23, 'name': 'macbook air', 'wholesale_price': 800, 'retail_price': 1000, 'sales': 40},
    {'product_id': 96, 'name': 'Python Workout', 'wholesale_price': 35, 'retail_price':75, 'sales': 1000},
    {'product_id': 97, 'name': 'Pandas Workout', 'wholesale_price': 35, 'retail_price':75, 'sales': 500},
    {'product_id': 15, 'name': 'banana', 'wholesale_price': 0.5, 'retail_price':1, 'sales': 300},
])

In [3]:
df = df.assign(current_net = (df['retail_price'] - df['wholesale_price']) * df['sales'])

In [4]:
# after 15% tax
df = df.assign(after_15 = (df['current_net'] * 0.85))

In [5]:
# after 20% tax
df = df.assign(after_20 = df['current_net'] * 0.80)

In [7]:
# after 25% tax
df = df.assign(after_25 = df['current_net'] * 0.75)

### Beyond 1

In [9]:
df['current_net'].apply(lambda c: c*0.75 if c > 20000 else c).sum()

np.float64(58150.0)

In [10]:
# longer way
def calc_tax(c):
    if c > 20000:
        return c * 0.75
    else:
        return c

df['current_net'].apply(calc_tax).sum()

np.float64(58150.0)

### beyond 2

In [13]:
# 25% tax retail > 80 10% on 80 > retail > 30 and no tax on others
df['after_tax'] = pd.cut(df['retail_price'],
                         bins = [0, 30, 80, df['retail_price'].max()],
                         labels=[1, 0.9, 0.75]).astype(np.float64)

df['final_net'] = df['current_net'] - df['after_tax']
df

,product_id,name,wholesale_price,retail_price,sales,current_net,after_15,after_20,after_25,after_tax,final_net
0,23,macbook air,800.0,1000,40,8000.0,6800.0,6400.0,6000.0,0.75,7999.25
1,96,Python Workout,35.0,75,1000,40000.0,34000.0,32000.0,30000.0,0.90,39999.10
2,97,Pandas Workout,35.0,75,500,20000.0,17000.0,16000.0,15000.0,0.90,19999.10
3,15,banana,0.5,1,300,150.0,127.5,120.0,112.5,1.00,149.00

### beyond 3

In [14]:
pd.options.display.float_format = '{:,.2f}'.format
df

,product_id,name,wholesale_price,retail_price,sales,current_net,after_15,after_20,after_25,after_tax,final_net
0,23,macbook air,800.00,1000,40,"8,000.00","6,800.00","6,400.00","6,000.00",0.75,"7,999.25"
1,96,Python Workout,35.00,75,1000,"40,000.00","34,000.00","32,000.00","30,000.00",0.90,"39,999.10"
2,97,Pandas Workout,35.00,75,500,"20,000.00","17,000.00","16,000.00","15,000.00",0.90,"19,999.10"
3,15,banana,0.50,1,300,150.00,127.50,120.00,112.50,1.00,149.00

## Notes

Record what you learned or alternative approaches here.